### ISSUE TITLE
Object naming

### ISSUE THREAD

**Issue by Julie-AnneTangena** [afrimapr/afrilearndata#1]
I find the naming slightly confusing.

I know this is a personal preference, but would it help to use underscores to separate the different sections of the names? ‘sf_afri_hway’ instead of ‘sfafrihway’. 
Or even easier afrihway_sf or afrihway. 

What do others think?

**Comment by andysouth** [comment]
Thanks @Julie-AnneTangena 
Good point, and following discussion in the meeting, I'm thinking of removing 'sf...' & 'rast...' parts to give : 
africountries
africontinent
afrihway
africapitals
afriwpop2020
afriwpop2000

I try to avoid underscores because they take a bit longer to type, but am open to considering.

What do you think @dickoa @Robinlovelace @anelda @LaurieLBaker @Paula-Moraga ?

**Comment by LaurieLBaker** [comment]
I'd agree. I think you could even spell out: afrihighway as it won't be too long and then people know what it is.

Similarly you could make it afripop2020 and afripop2000 and just mention in the documentation that it is from world pop?

**Comment by andysouth** [comment]
objects now with shorter names :-)
